[workspace.package]
version = "0.1.0"
license = "MPL-2.0 OR LGPL-2.1-or-later"
edition = "2021"
rust-version = "1.75"

[profile.release]
lto = true
codegen-units = 1

[workspace]
resolver = "2"
members = ["gufo-exif", "gufo-common", "gufo-jpeg", "tests", "gufo-xmp", "gufo"]

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
arithmetic_side_effects = "forbid"
cast_possible_truncation = "forbid"
cast_possible_wrap = "forbid"

[workspace.dependencies]
gufo-common = { version = "0.1.0", path = "gufo-common" }
gufo-exif = { version = "0.1.0", path = "gufo-exif" }
gufo-jpeg = { version = "0.1.0", path = "gufo-jpeg" }
gufo-xmp = { version = "0.1.0", path = "gufo-xmp" }
once_cell = "1.19.0"
paste = "1.0.15"
serde = { version = "1.0.202", features = ["derive"] }
tracing = "0.1"
thiserror = "1.0.61"
