
# cargo-vet config file

[cargo-vet]
version = "0.9"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.gnome-audited]
url = "https://gitlab.gnome.org/Teams/Releng/rust-supply-chain/-/raw/main/gnome-audited/audits.toml"

[imports.gnome-created]
url = "https://gitlab.gnome.org/Teams/Releng/rust-supply-chain/-/raw/main/gnome-created/supply-chain/audits.toml"

[imports.gnome-trusted]
url = "https://gitlab.gnome.org/Teams/Releng/rust-supply-chain/-/raw/main/gnome-trusted/supply-chain/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[policy.gufo]
audit-as-crates-io = true

[policy."gufo-common"]
audit-as-crates-io = true

[policy."gufo-exif"]
audit-as-crates-io = true

[policy."gufo-jpeg"]
audit-as-crates-io = true

[[exemptions.paste]]
version = "1.0.15"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.66"
criteria = "safe-to-deploy"

[[exemptions.xml-rs]]
version = "0.8.19"
criteria = "safe-to-deploy"
