[package]
name = "gufo-jxl"
version = "0.1.0"
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
gufo-common.workspace = true
jxl-bitstream = "0.4.0"
jxl-image = "0.9.0"
nom.workspace = true


[lints]
workspace = true
