[package]
name = "gufo-jpeg"
description = "Inspect JPEG image structure"
version.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
gufo-common.workspace = true
tracing.workspace = true
thiserror.workspace = true
jpeg-encoder = "0.6.0"
