[package]
version.workspace = true
name = "gufo-xmp"
license.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
xml-rs.workspace = true
thiserror.workspace = true
gufo-common.workspace = true
