[package]
name = "gufo"
description = "Gufo"
version.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
gufo-common = "0.1.0"
gufo-exif = "0.1.0"
gufo-jpeg = "0.1.0"

[lints]
workspace = true
