name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        rust:
          - "1.75"
          - "stable"

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Install rust ${{ matrix.rust }}
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ matrix.rust }}
        components: rustfmt, clippy
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test -- --nocapture
